### PR TITLE
👌 NEW: Collapsed cell css

### PR DESCRIPTION
**Pull request by AakashGfude**
fixes https://github.com/executablebooks/MyST-NB/issues/272

The most basic setup, with just css. as myst-nb does not have a `js` setup yet. Which is needed for this one to look and work nicely, something like in this page https://python.quantecon.org/linear_algebra.html#Vector-Operations .

@mmcky @choldgraf , should i make a more "professional" version of this by creating a js file in myst-nb. or do you think the js file will be better off in some other repo ?

Screen Shot 2020-11-04 at 10 28 23 am

### CODE REVIEW

**Comment by choldgraf** [comment]
this looks nice! just a quick thought, didn't we decide this made more sense in one of the themes? https://github.com/executablebooks/MyST-NB/issues/272#issuecomment-716872514

Or did you try it in the theme and decide it didn't make sense there?

**Comment by AakashGfude** [comment]
true @choldgraf . Actually since we are making this a tag, and there are some tag styles for code cells in `mystnb.css`. And also since @mmcky is more inclined towards `myst-nb` (from our discussions in slack). so I thought of doing it here first, and continuing the discussion on the best place and features list for it. 

Ohh, also the tag which I used is `collapse-cell`.

**Comment by AakashGfude** [comment]
I think we also agreed on making the height of the window, `20` in this case, configurable right?

Should we have a `show-more` button, like in this link : https://python.quantecon.org/linear_algebra.html#Vector-Operations . Which helps the user to see the whole code if expanded. or you like the scroll bar better?

**Comment by choldgraf** [comment]
Unless you really want it to be configurable, I think a reasonable first-step would be to default to whatever the Jupyter Notebook height is when the cell is in "scroll mode"

Wait I'm an idiot, I think this might already be implemented 😬 https://jupyterbook.org/content/layout.html?highlight=scroll#scrolling-cell-outputs

**Comment by AakashGfude** [comment]
Hahha. Problem solved it seems 😄  .
We should close this PR then, and ask @mmcky if he is happy with the existing one, and wants to close the issue https://github.com/executablebooks/MyST-NB/issues/272 , or make it configurable and then close it?

**Comment by mmcky** [comment]
thanks @choldgraf I went looking in the docs for something like that and didn't come across it. I kept going to "Formatting code outputs" rather than "Control the page layout". I might add a link from the former to the later section.

**Comment by choldgraf** [comment]
I think we should move this over to the code outputs section (which didn't exist when this feature was originally added I'd bet).

**Comment by choldgraf** [comment]
@mmcky wanna either make a PR or open an issue for this?

**Comment by choldgraf** [comment]
actually I'll just do it, I need an excuse to stop doomscrolling twitter right now

**Comment by mmcky** [comment]
@choldgraf I trust you saw the PR (given the comments). Sorry will try and link a bit better next time
https://github.com/executablebooks/jupyter-book/pull/1075

**Pull request closed without merging**
