### PR TITLE
css to align and float figure directives

### PR DESCRIPTION
**Pull request by najuzilu**
I've added some basic css to align figures using `figclass` option.

Here's a quick screenshot of the documentation I'd like to add to the `cli`:
Screen Shot 2020-04-08 at 3 20 55 PM

Would love to hear what people think about this @chrisjsewell @choldgraf

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Yeh I don't see any problem with that in principle 👍 
You need to add a new line to the bottom of the file to pass pre-commit (see [code style](https://myst-nb.readthedocs.io/en/latest/develop/contributing.html#code-style) for details)

Also why you are at it, it would be good to add some documentation on this option, and also on the CSS in general, e.g. a note on how people can override it: https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html

**Comment by choldgraf** [comment]
this sounds great to me - the one thing I'd double-check is that the aligning CSS works across multiple github themes (and in particular for the sphinx-book-theme)

**Comment by najuzilu** [comment]
@chrisjsewell should I include this information in the `MyST-NB` doc or `cli` doc?
@choldgraf it works great with `sphinx-book-theme`. I'll double check that it works across multiple github themes too.

**Comment by choldgraf** [comment]
I think we'll have to do both, for the documentation

**Comment by chrisjsewell** [comment]
Yep add it here first and we’ll take it from there

**Comment by choldgraf** [comment]
@najuzilu I just realized that this fix is probably better in the [`pydata-sphinx-theme`](https://github.com/pandas-dev/pydata-sphinx-theme) as well as the `sphinx-book-theme`, rather than being in MyST-NB, because these fixes are not unique to Jupyter Notebooks or their outputs.

I think the path forward would be to:

1. From the `sphinx-book-theme` take the "standard" figure CSS rules (the `align-` ones that are triggered with `:align:` and the "float" ones that are triggered with `:figclass:` and *move* them into `pydata-sphinx-theme` (since the book theme inherits from pydata, we'll get the CSS from there).
2. For the "extra" CSS classes (AKA, the sidebar ones), put those in the `sphinx-book-theme`. They feel a bit more customized to the book theme to me.

**Comment by najuzilu** [comment]
@choldgraf sounds good. Will do this now. :-)

**Comment by choldgraf** [comment]
hey all - if I recall this is now in sphinx-book-theme, is that right @najuzilu ?

**Comment by najuzilu** [comment]
@choldgraf yes. I'll go ahead and close this issue.

**Pull request closed without merging**
