### PR TITLE
Some small adjustments

### PR DESCRIPTION
**Pull request by zmoon**
For https://github.com/executablebooks/MyST-NB/issues/267.

### CODE REVIEW

**Comment by zmoon** [comment]
Some of the mentions of other parts of the code could be cross-references instead of ` ``text`` `. I could do that if that is desired.

**Comment by chrisjsewell** [comment]
Hey @zmoon thanks for the PR, is it ready for review? Since you currently have it set as Draft

**Comment by zmoon** [comment]
Hi @chrisjsewell I suppose I was waiting to see if there was interest in the cross-references. If not it is ready.

**Comment by chrisjsewell** [comment]
Oh yeh sorry. Well I won't say no to it, if you have the time 😄

**Comment by zmoon** [comment]
So I only really found one place where cross-reference made sense. The rest were docutils, which I suppose doesn't work with intersphinx.

**Comment by michaelweinold** [comment]
@agoose77, in case you want to clean up the outstanding PRs: The docstring updates in this PR are all outdated (either fixed, or functions have been removed/replaced). Best to close it and the associated issue.

**Comment by bsipocz** [comment]
As per the previous comment, that the typos have been fixed in the meantime, I'm closing this PR now. 

Thank you for opening the PR nevertheless.

**Pull request closed without merging**
