### PR TITLE
✨ Add configuration for traceback in stderr

### PR DESCRIPTION
**Pull request by chrisjsewell**

### CODE REVIEW

**Comment by chrisjsewell** [comment]
I f we are using RTD for CLI, we can probably remove circleci (now that https://github.com/readthedocs/readthedocs.org/issues/7240 is closed)
weird that circleci passes and RTD does not, clearly something in the environment

**Comment by chrisjsewell** [comment]
ok weird, now everything passes, but the outputs are still not there.
If you download the notebook from the footnote in: https://myst-nb--218.org.readthedocs.build/en/218/use/hiding.html, the matplotlib images have actually been created (as `image/png` MIMEs) but these are not making their way into the HTML output

**Comment by chrisjsewell** [comment]
Also @choldgraf can you add https://readthedocs.org/profiles/ebp-bot as a maintainer of the RTD

**Comment by choldgraf** [comment]
@chrisjsewell I added the bot!

**Comment by chrisjsewell** [comment]
I don't think this fully fixes the original issue, but I am going to merge and open a new PR

**Pull request merged**
