### PR TITLE
TST: fail on warnings

### LINKED ISSUE #645: Pending deprecation warning in Sphinx 8
See CI in sphinx-book-theme

### PR DESCRIPTION
**Pull request by bsipocz**
This should fix #645

### CODE REVIEW

**Comment by bsipocz** [comment]
The configuration for failing on warnings is all OK, but the actual fix for the deprecation is a dead end currently as we run into a `ModuleNotFoundError` for the reader function we try to use it for. 
However, there are some discussion upstream about the possible un-deprecation of it.

**Comment by bsipocz** [comment]
For context and recent discussion about the deprecation and possible un-deprecation see https://github.com/sphinx-doc/sphinx/issues/13083

**Comment by bsipocz** [comment]
There are still tons of windows issues, and I have to rely on CI to get those sorted out, so I'm sorry for the upcoming flood of spammy notifications originating from this PR.

**Comment by bsipocz** [comment]
@agoose77 - This is good to go. I fully expect this to provide a lot of help with picking up the compatibility issues early on, the ones we run into now after users report them.

**Comment by agoose77** [comment]
LGTM! Thanks @bsipocz and @lucascolley!

**Comment by agriyakhetarpal** [comment]
Thanks! Is there a release with this change planned soon? If there's any additional help I can provide on recent PRs, I'm happy to.

**Pull request merged**
