### PR TITLE
🔧 MAINTAIN: Changed test assert text to Execution Succeeded

### PR DESCRIPTION
**Pull request by AakashGfude**
changing to `assert "Execution Succeeded"` instead of `assert "Executing"` in `test_relative_path_cache` and `test_relative_path_force`.

### CODE REVIEW

**Comment by choldgraf** [comment]
argg damn - looks like you've unconvered a bug that I hadn't properly tested for. Thanks for catching this

**Comment by AakashGfude** [comment]
Hey @choldgraf, what is the status on this one? Should I close this PR? as it was created only to test the bug. Let me know if you want me to look at anything regarding the relative path cache functionality. Then I will work on this branch itself.

**Comment by choldgraf** [comment]
Ummm, I'm not really sure haha. Been a while since I've touched this one, but I don't think any major changes have happened since then

**Comment by AakashGfude** [comment]
@choldgraf been a while since we did anything with this. Looks like the build is failing though in this one, because of the sphinx cache from the previous build. 
WIll clear the cache just before this runs.

**Comment by AakashGfude** [comment]
Have changed the assert statement from `Execution Succeeded` to **not**  `Execution Failed`. As jupyter-cache does not log Execution Succeeded for single pages.

**Comment by choldgraf** [comment]
cool - let's merge it in as all the tests are happy 🌈

**Pull request merged**
