### PR TITLE
adding a timeout for execution

### PR DESCRIPTION
**Pull request by AakashGfude**
**NOTE**:-  This PR should only be merged after this one https://github.com/ExecutableBookProject/jupyter-cache/pull/48

Hey @chrisjsewell , should we give a timeout of -1 like this? because a few notebooks where failing with timeout error. Or do we want to control its value from somewhere?

### CODE REVIEW

**Comment by AakashGfude** [comment]
closes https://github.com/ExecutableBookProject/MyST-NB/issues/139

**Comment by chrisjsewell** [comment]
> closes #139

Note that this, I believe, needs to be in the initial comment, to be auto-added to the linked issues.

**Comment by chrisjsewell** [comment]
See comment in ExecutableBookProject/jupyter-cache#48

**Comment by AakashGfude** [comment]
@choldgraf Note that the tests here will fail until the PR in jupyter-cache is merged

**Comment by choldgraf** [comment]
ah nice! The tests here look good, though I think we should probably be testing in jupyter-cache as well. Wanna copy over (or more over) some of the testing functionality that is here and put it into jupyter-cache? I think in general its good to test functionality within the tool that provides it, instead of in a downstream tool that builds on top of jupyter-cache.

**Comment by AakashGfude** [comment]
@choldgraf ahh. good point. I will do the necessary changes.

**Comment by AakashGfude** [comment]
@choldgraf  Thanks for the merge in `jupyter-cache`. Once, we release a new version of `jupyter-cache`, we can get back to the tests in this PR.

**Comment by choldgraf** [comment]
nice! is there anything preventing a new release of jupyter-cache from happening? If not can we just cut a new release? I am not as familiar with that codebase

**Comment by AakashGfude** [comment]
@choldgraf I don't think there is anything preventing us. We can safely do a new release i think.

**Comment by AakashGfude** [comment]
Looks, like @chrisjsewell , just made a new release. Thanks

**Comment by AakashGfude** [comment]
@choldgraf should I push a new dummy commit for the CI to rerun the tests or we can re-trigger it somewhere from the server.
Not whining, but my laptop broke down yesterday, and I am trying to fix it. So, wont be able to make a push for a couple days I think. I will make a dummy push as soon as possible, if we can't re-trigger the CI tests.

**Comment by choldgraf** [comment]
Feel free to push a dummy commit - that'll just trigger everything

**Comment by AakashGfude** [comment]
@choldgraf this looks good now.

**Comment by choldgraf** [comment]
wohooo! thanks @AakashGfude for pushing this through!

**Pull request merged**
