### PR TITLE
🐛 FIX: remove cell background-color CSS for cells

### PR DESCRIPTION
**Pull request by melaniewalsh**
This is related to my previous pull request #261 and previous Jupyter Book issue executablebooks/jupyter-book#905, which was that Bokeh plot toolbars were not showing up. My previous pull request fixed the toolbar issue, but I subsequently realized that Bokeh hover tooltips were showing up with transparent backgrounds, which is not how they should appear.

Removing the cell background-color entirely fixes the issue with Bokeh hover tooltips, and it doesn't seem like this fix is causing any other problems with the cells in my personal Jupyter Book.

## Issue 
Bokeh plot with cell background-color as `transparent`

Screen Shot 2020-10-05 at 10 21 16 AM

## Sugested Fix
Bokeh plot with cell background-color removed

Screen Shot 2020-10-05 at 10 21 01 AM

### CODE REVIEW

**Comment by choldgraf** [comment]
this seems like a reasonable fix to me! Any time we can remove code and retain the same behavior is a win to me :-)

I'm not sure why the tests didn't pass, it doesn't seem like it should be related to this, I'll try restarting them

**Comment by chrisjsewell** [comment]
> I'm not sure why the tests didn't pass, it doesn't seem like it should be related to this, I'll try restarting them

No it was a change in jupyter-sphinx 😒, that needs fixing in the tests (which I haven't merged yet, as was getting round to fixing).

**Comment by choldgraf** [comment]
argg - thanks for the diagnosis @chrisjsewell

**Comment by akhmerov** [comment]
Ah, that's because the saving is now deferred to nbconvert, and so is its warning control. Anything TBD on jupyter-sphinx side?

**Comment by chrisjsewell** [comment]
nah thats fine thanks. I think just have to change the test assertions

**Comment by chrisjsewell** [comment]
I've pinned jupyter-sphinx to the penultimate version for now, so that we can get these PRs merged.
Then I'll address the failing tests hopefully in the next week or so, when I have a bit of a focus on myst-nb improvements

**Comment by chrisjsewell** [comment]
Oh and by the way, why are you studying Game of Thrones!? GoT is dead to me since the abomination that was season 8 haha; yes, yes it's also a book, but since GRRM will be with the angels before he finishes it, that's probably the only ending we are going to get lol.

**Comment by melaniewalsh** [comment]
Haha @chrisjsewell! I've been using Game of Thrones characters to teach network analysis https://melaniewalsh.github.io/Intro-Cultural-Analytics/Network-Analysis/Network-Analysis.html The GOT data works pretty well because it inspires a lot of passionate responses, not unlike yours 😉

**Comment by choldgraf** [comment]
Season 8? I'm pretty sure there was no Season 8 - the producers decided that it was best if we just left it off at Season 7 and all moved on with our leaves. 👑

**Comment by chrisjsewell** [comment]
While your at it, you can cut out most of season 7 😂

**Comment by melaniewalsh** [comment]
Quick question. Has this change been integrated into the latest version of Jupyter Book? I still have to manually remove `background-color: transparent` from `mystnb.css` every time I build my book.

**Comment by chrisjsewell** [comment]
Heya no I don't believe it has, I'm just working on some changes to myst-nb, so there should be a new version out shortly

**Comment by melaniewalsh** [comment]
Awesome, thanks, @chrisjsewell! Just wanted to check 👌

**Comment by AakashGfude** [comment]
Guys, this change in CSS is making the background-color turn yellow for code-cells. ex: https://5ff580ff1bec79c49f4be5b2--nostalgic-wright-5fa355.netlify.app/geom_series.html . I believe it is not intended?

**Comment by choldgraf** [comment]
well it's mostly just *removing* opinion about the background of cells and leaving it up to the underlying theme a bit more. If you wanna make a PR that fixes this in a more reliable way (and maybe also address #287 while we're at it), that'd be awesome

**Pull request merged**
