### PR TITLE
UPGRADE: myst-parser 1.0

### PR DESCRIPTION
**Pull request by aleivag**
This updates the myst-parser dependency to ~1.0

The changes are simple:

- Update imports
- Deprecate DOCUTILS_EXCLUDED_ARGS and implemented the omit: [docutils]
- Black also did some formatting

I know very little about how this uses myst-parser all i know is that my jupyter-book compiles and uses latest features of myst parser using this. the doc generator seems broken on master , so i cant really tell if this is me or just broken on base rev, please advice !

### CODE REVIEW

**Comment by mgaitan** [comment]
I've tried this. It forced to downgrade `sphinx` from 6.1.0 to 5.3.0. why ?

and I got this error 

```
# Sphinx version: 5.3.0
# Python version: 3.10.6 (CPython)
# Docutils version: 0.19 
# Jinja2 version: 3.0.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/tin/.virtualenvs/shiphero/lib/python3.10/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/tin/.virtualenvs/shiphero/lib/python3.10/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/home/tin/.virtualenvs/shiphero/lib/python3.10/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/tin/.virtualenvs/shiphero/lib/python3.10/site-packages/sphinx/registry.py", line 472, in load_extension
    metadata = setup(app)
  File "/home/tin/.virtualenvs/shiphero/lib/python3.10/site-packages/myst_nb/__init__.py", line 8, in setup
    from .sphinx_ext import sphinx_setup
  File "/home/tin/.virtualenvs/shiphero/lib/python3.10/site-packages/myst_nb/sphinx_ext.py", line 23, in <module>
    from myst_nb.sphinx_ import (
  File "/home/tin/.virtualenvs/shiphero/lib/python3.10/site-packages/myst_nb/sphinx_.py", line 16, in <module>
    from myst_parser.mdit_to_docutils.sphinx_ import SphinxRenderer, create_warning
ImportError: cannot import name 'create_warning' from 'myst_parser.mdit_to_docutils.sphinx_' (/home/tin/.virtualenvs/shiphero/lib/python3.10/site-packages/myst_parser/mdit_to_docutils/sphinx_.py)
```

**Comment by aleivag** [comment]
hi, what did you did to get this error (how do i reproduce)? 

> I've tried this. It forced to downgrade sphinx from 6.1.0 to 5.3.0. why ?

Don't know, nothing in the PR sets the version of sphinx, so i guess is within the allowed versions , if you give me the command you used i'm happy to check

**Comment by choldgraf** [comment]
I took a look at the CI jobs and noticed a few errors:

### mypy errors in our pre-commit job

Apparently MyST-parser introduced a new way to construct `create_warnings` and it is checking for a particular warning type. The myst-parser warnings object is here:

https://github.com/executablebooks/MyST-Parser/blob/a784880c7fbd893566087b83deec081376740e2c/myst_parser/warnings_.py#L10-L26

Here's the error:

```
myst_nb/core/render.py:99: error: Argument "subtype" to "create_warning" of "DocutilsRenderer" has incompatible type "str"; expected "MystWarnings"  [arg-type]
myst_nb/core/render.py:225: error: Unexpected keyword argument "wtype" for "create_warning" of "DocutilsRenderer"  [call-arg]
/home/runner/.cache/pre-commit/repofub48hzv/py_env-python3.9/lib/python3.9/site-packages/myst_parser/mdit_to_docutils/base.py:162: note: "create_warning" of "DocutilsRenderer" defined here
myst_nb/core/render.py:225: error: Unexpected keyword argument "wtype" for "create_warning" of "DocutilsRenderer"  [call-arg]
myst_nb/core/render.py:228: error: Argument "subtype" to "create_warning" of "DocutilsRenderer" has incompatible type "str"; expected "MystWarnings"  [arg-type]
/home/runner/.cache/pre-commit/repofub48hzv/py_env-python3.9/lib/python3.9/site-packages/myst_parser/mdit_to_docutils/base.py:162: note: "create_warning" of "DocutilsRenderer" defined here
myst_nb/core/render.py:228: error: Argument "subtype" to "create_warning" of "DocutilsRenderer" has incompatible type "str"; expected "MystWarnings"  [arg-type]
myst_nb/core/render.py:979: error: Unexpected keyword argument "wtype" for "create_warning" of "DocutilsRenderer"  [call-arg]
/home/runner/.cache/pre-commit/repofub48hzv/py_env-python3.9/lib/python3.9/site-packages/myst_parser/mdit_to_docutils/base.py:162: note: "create_warning" of "DocutilsRenderer" defined here
myst_nb/core/render.py:979: error: Unexpected keyword argument "wtype" for "create_warning" of "DocutilsRenderer"  [call-arg]
myst_nb/core/render.py:983: error: Argument "subtype" to "create_warning" of "DocutilsRenderer" has incompatible type "str"; expected "MystWarnings"  [arg-type]
/home/runner/.cache/pre-commit/repofub48hzv/py_env-python3.9/lib/python3.9/site-packages/myst_parser/mdit_to_docutils/base.py:162: note: "create_warning" of "DocutilsRenderer" defined here
myst_nb/core/render.py:983: error: Argument "subtype" to "create_warning" of "DocutilsRenderer" has incompatible type "str"; expected "MystWarnings"  [arg-type]
myst_nb/sphinx_.py:305: error: Unexpected keyword argument "wtype" for "create_warning" of "DocutilsRenderer"  [call-arg]
/home/runner/.cache/pre-commit/repofub48hzv/py_env-python3.9/lib/python3.9/site-packages/myst_parser/mdit_to_docutils/base.py:162: note: "create_warning" of "DocutilsRenderer" defined here
myst_nb/sphinx_.py:310: error: Argument "subtype" to "create_warning" of "DocutilsRenderer" has incompatible type "str"; expected "MystWarnings"  [arg-type]
myst_nb/docutils_.py:306: error: Unexpected keyword argument "wtype" for "create_warning" of "DocutilsRenderer"  [call-arg]
/home/runner/.cache/pre-commit/repofub48hzv/py_env-python3.9/lib/python3.9/site-packages/myst_parser/mdit_to_docutils/base.py:162: note: "create_warning" of "DocutilsRenderer" defined here
myst_nb/docutils_.py:312: error: Argument "subtype" to "create_warning" of "DocutilsRenderer" has incompatible type "str"; expected "MystWarnings"  [arg-type]
myst_nb/docutils_.py:337: error: Unexpected keyword argument "wtype" for "create_warning" of "DocutilsRenderer"  [call-arg]
/home/runner/.cache/pre-commit/repofub48hzv/py_env-python3.9/lib/python3.9/site-packages/myst_parser/mdit_to_docutils/base.py:162: note: "create_warning" of "DocutilsRenderer" defined here
myst_nb/docutils_.py:342: error: Argument "subtype" to "create_warning" of "DocutilsRenderer" has incompatible type "str"; expected "MystWarnings"  [arg-type]
```

### Regression test breakages

This one is probably simple to fix, there are some regression test changes detected:

For example:

```diff
-        <footnote_reference auto="1" ids="footnote-reference-1" refid="a">
+        <footnote_reference auto="1" ids="id1" refid="a">
             1
          
-        <footnote_reference auto="1" ids="footnote-reference-2" refid="b">
+        <footnote_reference auto="1" ids="id2" refid="b">
             2
```

To fix these you generally just need to delete the corresponding regression test file, and then re-run the tests.

**Comment by kloczek** [comment]
I've been trying to use that PR on top of 0.17.2 but looks like PR needs to be rediffed
```console
+ /usr/bin/gzip -dc /home/tkloczko/rpmbuild/SOURCES/python-myst-nb-0.17.2.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd MyST-NB-0.17.2
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/python-myst-nb-UPGRADE-myst-parser-1.0.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch -f
1 out of 2 hunks FAILED -- saving rejects to file myst_nb/core/read.py.rej
1 out of 6 hunks FAILED -- saving rejects to file myst_nb/core/render.py.rej
1 out of 4 hunks FAILED -- saving rejects to file myst_nb/docutils_.py.rej
2 out of 3 hunks FAILED -- saving rejects to file myst_nb/sphinx_.py.rej
2 out of 2 hunks FAILED -- saving rejects to file pyproject.toml.rej
```

**Comment by mmcky** [comment]
I need to take a closer look at how `MystWarnings` is working in `create_warnings`. I will need to loop back around to this PR in a couple days.

**Comment by mmcky** [comment]
@chrisjsewell I have tried to mirror the new `warnings_.py` structure that has been put in place in `myst-parser` but I am getting `mypy` issues due to the mix of `MystWarnings` and `MystNBWarnings`. The render objects from myst-parser is returning `MystWarnings` when I need a union of both. 

```
myst_nb/core/render.py:100: error: Argument "subtype" to "create_warning" of "DocutilsRenderer" has incompatible type "MystNBWarnings"; expected "MystWarnings"  [arg-type]
```

Would be interested in thoughts on how to resolve this if you've got time. Thanks.

**Comment by krassowski** [comment]
In short term, would it be acceptable to just suppress these warnings with `type: ignore`?

**Comment by choldgraf** [comment]
I'm personally fine with that - it feels like the pain people are feeling with a version capped and outdated MyST parser is stronger than the pain they might feel if some problem occurs because of this type mismatch.

I'd suggest we just try to get these changes in quickly and cut a release. Then keep an eye for new issues that might be related to this and provide guidance (inc telling people to version cap) if so.

**Comment by Yoshanuikabundi** [comment]
I've fixed the type errors in a PR to this branch: https://github.com/aleivag/MyST-NB/pull/1

I did find a couple of changes to behavior from this process.

Just haven't heard back from @aleivag yet.

**Comment by choldgraf** [comment]
Thanks for making that effort @Yoshanuikabundi - in that case I'd recommend the following course of action:

- Give @aleivag a few days to review and merge @Yoshanuikabundi's PR.
- If he doesn't respond in that time, I'll apply @Yoshanuikabundi's commit here (w/ attribution) and will push to @aleivag's branch.
- We can then see if the test suite is happy.

@Yoshanuikabundi what were the behavior changes that you noticed?

**Comment by chrisjsewell** [comment]
(FYI I'm not currently maintaining this repo: https://github.com/executablebooks/meta/issues/961)

**Comment by choldgraf** [comment]
OK I've cherry-picked and pushed the two commits from @Yoshanuikabundi's PR to this branch. Let's see how that impacts tests and such.

**Comment by Yoshanuikabundi** [comment]
@choldgraf I was initially confused about this error because I don't see how anything I did could cause it (and also I don't understand it at all), so I checked out the commit on this branch before I did any work (a150582232cc07d33d519152e3697388667ead34) and I get a very similar error locally there: 

```
_____________________________ ERROR collecting tests/test_docutils.py ______________________________
tests/test_docutils.py:11: in <module>
    from myst_nb.docutils_ import Parser
myst_nb/docutils_.py:73: in <module>
    class Parser(MystParser):
myst_nb/docutils_.py:82: in Parser
    create_myst_settings_spec(NbParserConfig, "nb_"),
.soap/test/lib/python3.8/site-packages/myst_parser/parsers/docutils_.py:211: in create_myst_settings_spec
    return tuple(
.soap/test/lib/python3.8/site-packages/myst_parser/parsers/docutils_.py:212: in <genexpr>
    attr_to_optparse_option(at, getattr(defaults, at.name), prefix)
.soap/test/lib/python3.8/site-packages/myst_parser/parsers/docutils_.py:200: in attr_to_optparse_option
    at_options, default_str = _attr_to_optparse_option(attribute, default)
.soap/test/lib/python3.8/site-packages/myst_parser/parsers/docutils_.py:185: in _attr_to_optparse_option
    raise AssertionError(
E   AssertionError: Configuration option execution_mode not set up for use in docutils.conf.
```

So I think this is might be from a change in a dependency? I'm looking into it but I'm in unfamiliar territory.

**Comment by choldgraf** [comment]
I suggest we roll back or pin as many non-myst-parser versions as we can until we get the tests passing, and then merge and iterate selectively from there.

This seems to be where the field that generates this error is coming from:

https://github.com/executablebooks/MyST-NB/blob/5d972446636b631dd5777f286420cce3e906cfce/myst_nb/core/config.py#L138-L146

cc also @agoose77 in case any of this is familiar? I think he's looked through the myst-nb codebase before.

**Comment by LecrisUT** [comment]
Wait a minute, are these failures all about `mypy`? These should be in `pre-commit` not in the actual `pytest` so things are not getting confused. But hey, tests are starting to pass :)

**Comment by agoose77** [comment]
It is related to typing, but not mypy; `myst-parser` uses the type signatures of the config objects to perform some translation. In `myst-nb` we used `from __future__ import annotations`, which has the effect of storing type signatures as strings. This is not something that `myst-parser` anticipates, and therefore fails. We can fix this on the `myst-parser` side, but that would require a new release of `myst-parser`. For now, then, we can just update `myst-nb` to use non-string annotations for this module.

**Comment by LecrisUT** [comment]
Can the typing verification be excluded from pytest or handled in a different tool? That way at least we can separate the functional tests that would use dynamic typing. The typing tests can be a bit finicky with different python versions, package versions, etc.

**Comment by choldgraf** [comment]
I think our strategy here is that we should optimize for getting these versions bumped in a way that will not confuse users. If tests are failing only because we are not meeting some strict requirement of the test that may not actually translate to an impaired user UX, I am okay loosening the test restriction or using a hacky workaround.

**Comment by agoose77** [comment]
To be clear, the tests are failing because we broke something by moving to stringized annotations. I've reverted that part of the PR, which should make the tests pass :crossed_fingers:

**Comment by LecrisUT** [comment]
For sure that sounds like a functionality issue that needs to be addressed. I was thinking about having the tests be a bit more separated so it is easier to read. At some point the tests did not start to run because it detected bad typing errors, which does not tell us if the tests would actually fail for the user or not. Having those checks are great to have and address, but have them a bit separate so its easier to judge which one to prioritize and which ones can/should be resolved by dropping older version support

**Comment by choldgraf** [comment]
Amazing! Thanks for this iteration folks. It looks like the only "failing" thing is the documentation having a few broken cross-reference links because the myst docs have changed. I would be fine merging this as-is in order to get it in. But if anyone wants to quickly fix those I'm happy to review and merge.

**Comment by Yoshanuikabundi** [comment]
I've pushed fixes for the Intersphinx links that are breaking RTD to my branch: https://github.com/Yoshanuikabundi/MyST-NB/commits/upgrade-to-1

The docs build locally for me without warnings and I've spot checked that most of the links still go to the same places. Was just a matter of updating to the new syntax for specifying Intersphinx links and fixing some ambiguities.

Thanks for taking a look @agoose77, I don't know that I ever would have figured that out!

**Review by choldgraf — APPROVED** [review]
OK I've pushed the latest patch from @Yoshanuikabundi and now all of the tests are happy - the codecov isn't but I think that's OK because this isn't adding functionality, just refactoring and updating because of upstream changes.

Thanks so much everybody for helping out here!

**Pull request merged**
