### PR TITLE
Support sphinx 7

### PR DESCRIPTION
**Pull request by LecrisUT**
There is a dependency hell to resolve here due to the testing requirements. However this package is a blocking requirement for various other packages downstream. These test requirements should be addressed.

See my fork's PR for current status https://github.com/LecrisUT/MyST-NB/pull/1

### CODE REVIEW

**Comment by choldgraf** [comment]
If you can get all of the tests passing here then I'm happy to take a look and merge. MyST-NB hits a lot of the inner Sphinx machinery and so new Sphinx releases tend to break MyST-NB. The PR with the most activity on getting various versions bumped is here:

- #479

**Comment by LecrisUT** [comment]
I think it is best to focus on #479 because of Sphinx7 it is mostly dependency issues. I will then rebase on top of that and see what surprises we get from the other CIs. Sounds like a good plan?

**Comment by choldgraf** [comment]
agreed - we need to get this stack upgraded in general and that is a big blocker

**Comment by LecrisUT** [comment]
Applied #479 temporarily so we can see the broader tests after that is applied

**Comment by LecrisUT** [comment]
Great, everything seems to be working with that branch and in this PR it's only the Sphinx7 dependency issue that I wanted to highlight and address.
```
jupytext 1.14.6 depends on markdown-it-py<3.0.0 and >=1.0.0
    myst-parser 2.0.0 depends on markdown-it-py~=3.0
    mdit-py-plugins 0.4.0 depends on markdown-it-py<4.0.0 and >=1.0.0
```
jupytext issue is being slowly handled: https://github.com/mwouts/jupytext/issues/1075

**Comment by LecrisUT** [comment]
Jupytext pushed a new version so now all dependencies are satisfied. I restarted rhe CI locally, but found rhat 3.11 is failing

**Comment by choldgraf** [comment]
I've just merged in the MyST-Parser bump, and updated this branch to use it. Just FYI!

**Comment by LecrisUT** [comment]
Ok, I'll rebase it. In a sec. Keep an eye out to restart the CI

**Comment by LecrisUT** [comment]
Oh, all tests are green on my fork :thinking:

**Review by choldgraf — APPROVED** [review]
Woot! It looks like it is happy :-) 

Thanks for this contribution ✨

**Comment by LecrisUT** [comment]
Great, anything else before pushing a new tag?

**Pull request merged**
